name: InTime
main: de.homerbond005.intime.InTime
author: HomerBond005
version: '@PROJECT_VERSION@'
softdepend: [ApluginThatDoesntExistAndWillNeverDo]
commands:
    intime:
        description: Reload InTime